### ISSUE TITLE
跪求一份RTL wscd的源码

### ISSUE THREAD

**Issue by iEngne** [Carl-5535/carl-5535.github.io#1]
本人最新在集成RTL的WPS功能，发现代理商给的SDK缺少wscd的源码，上网搜索找到了您发布的“WPS功能调试”的博客，发现您这边有源码，请问wscd的源码还有吗？可否发一份给我，我的邮箱**septe2n@foxmail.com**，感谢感谢！

**Comment by iEngne** [comment]
代码商已经给了代码，Done

**Comment by Carl-5535** [comment]
Hi iEngne,

不好意思，我刚看到你的留言。
恭喜你拿到了厂商的代码。
因为我们使用的芯片是代理商处购买的(只提供芯片)，驱动我使用的是在CSDN上购买的一份。
如果你有需要请再告诉我，我发送给你

Thanks
Carl
